synctio/flashcards/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
   path('home/', views.home, name="home"),
#    path('deck-api/', views.DeckApi.as_view(), name="deck-api"),
    #path('formview/', views.FlashcardFormView.as_view(), name="flashcard-view"),
   # path("flashcard-detail/<str:pk>/", views.flashcardDetail, name="flashcardDetail"),
  #  path("flashcard-update/<str:pk>/", views.flashcardUpdate, name="flashcardUpdate"),
 #   path("flashcard-delete/<str:pk>/", views.flashcardDelete, name="flashcardDelete"),
#    path("api-overview/", views.apiOverview, name="apiOverview"),
 #   path("flashcard-list/", views.FlashcardList, name="flashcardList"),
#    path("flashcard-create/", views.flashcardCreate, name="flashcardCreate"),
 #   path("deck/<str:pk>/", views.deckView, name="deck"),
   path('flashcard-create-view/', views.flashcardCreateView, name="flashcardCreateView"),
   path('deck-view/<str:pk>/', views.deckView, name="deck"),
 #   path('update-json-deck/<str:pk>/', views.deckView, name="deck"),
   path('update-json-flashcard/<str:pk>/', views.updateJsonFlashcard, name="updateJsonDeck"),
  #  path('flashcard-detail/<str:pk>/', views.FlashcardDetail.as_view(), name="flashcard-detail"),
   path('delete-json-flashcard/<str:pk>/', views.deleteJsonFlashcard, name="flashcard-detail"),
   path('flashcard-list/<str:pk>/', views.FlashcardList, name="flashcard-list"),
   #re_path('^flashcard-list/(?P<deck>.+)/$', views.FlashcardList.as_view(), name="flashcard-list"),
#   re_path('^deck-detail/(?P<pk>\d+)/$', views.DeckDetail.as_view(), name="flashcard-detail"),
   #path('deck-list/', views.DeckList.as_view()),
   #path('folder-detail/<str:pk>/', views.FolderDetail.as_view(), name="flashcard-detail"),
   #path('folder-list/', views.FolderList.as_view()),
   path('deck-json-update/<str:pk>/', views.updateJsonDeck, name="UpdateJsonDeck"),
   path('deck-detail/<str:pk>/', views.DeckDetail, name="deck-detail"),
   #path('create-deck/', views.createDeck, name="createDeck"),
   #path('create-flashcard/', views.createFlashcard, name="createFlashcard"),
   #path('update-deck/<str:pk>/', views.updateDeck, name="updateDeck"),
   path('delete-deck/<str:pk>/', views.deleteDeck, name="deleteDeck"),
   path('delete-folder/<str:pk>/', views.deleteFolder, name="deleteFolder"),
   path('flashcardplay/<str:pk>/', views.flashcardplayview, name="flashcardplay"),
    # path('flashcardplayapi/', views.flashcardfindapiview, name="flashcardplayapi"),
   path('flashcardwriteapi/<str:pk>/', views.flashcardwriteview, name="flashcardwriteapi"),
   path('deckCreateEmpty/', views.deckCreateEmpty, name="deckCreateEmpty"),
   path('folderCreateEmpty/', views.folderCreateEmpty, name="folderCreateEmpty"),
   path("windblowing/<str:pk>/", views.flashcardWordBlowing, name="windblowing"),
]

synctio/synctio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  #  path('admin/defender/', include('defender.urls')), # defender admin
    path('admin/', admin.site.urls),
    path("", include("accounts.urls")),
    path("", include("flashcards.urls")),
    path("", include("openaiapi.urls")),
    path("", include("schedule.urls")),
]

synctio/flashcards/models.py
from django.db import models
from django.contrib.auth.models import User
import html.entities

# Create your models here.

class Folder(models.Model):
    previous_folder=models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    def __str__(self):
        return self.name

class Deck(models.Model):
    folder =models.ForeignKey(Folder, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name= models.CharField(max_length=500, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering =['-updated', '-created']
    def __str__(self):
        return str(self.id)


class Flashcard(models.Model):
    deck=models.ForeignKey(Deck, on_delete=models.CASCADE)
    key= models.CharField(max_length=1000)
    answer=models.CharField(max_length=2000, null=True, blank=True)
 #   image=models.ImageField(upload_to="flashcards/", blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering =['-created']
#    def __str__(self):
 #       return self.id

class FlashcardImpression(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name="flashcardKnowledge_users")
    flashcard=models.ForeignKey(Flashcard, on_delete=models.CASCADE, related_name="flashcardKnowledge_flashcards")
    review=models.CharField(default="0",max_length=1)
    #levelknown = models.IntegerField(default=0)
    #leveltried = models.IntegerField(default=0)

  #  def __str__(self):
   #     return self.id

synctio/flashcards/forms.py
from django.forms import ModelForm

from .models import Deck, Folder, Flashcard, FlashcardImpression
from django import forms

#class DeckIdForm(forms.Form):
 #   flashcard=forms.IntegerField(
  #      label="flashcard",
   #     widget=forms.TextInput(
    #        attrs={
     #           "id":"flashcardknowledge-flashcard",
      #      }
       # ),
    #)

class createFolderEmpty(ModelForm):
    previous_folder=forms.CharField(
        max_length=1000000,
        label="previous_folder",
        widget=forms.TextInput(
            attrs={
                "id":"previous_folder",
            }
        ),
    )
    class Meta:
        model = Folder
        fields = [
            "name",
            "description",
        ]

class createDeckEmpty(ModelForm):
    folder=forms.CharField(
        max_length=1000000,
        label="folder",
        widget=forms.TextInput(
            attrs={
                "id":"folder",
            }
        ),
    )
    class Meta:
        model = Deck
        fields = [
            "name",
            "description"
        ]
        

class findFlashcardForm(forms.Form):
    flashcard=forms.IntegerField(
        label="flashcard",
        widget=forms.TextInput(
            attrs={
                "id":"flashcardknowledge-flashcard",
            }
        ),
    )
    review=forms.ChoiceField(
        label="review",
        choices=[
            ("1","1"),
            ("0","0"),
            ("2","2"),
        ],
        widget=forms.RadioSelect(
            attrs={
 #               "class":"form-control",
                "id":"flashcardknowledge-review",
            }
        ),
    )

class FolderForm(ModelForm):
    class Meta:
        model = Folder
        fields = [
            "previous_folder",
            "name",
            "description",
        ]



class FlashcardForm(ModelForm):
    class Meta:
        model=Flashcard
        fields=[
            "deck",
            "key",
            "answer",
        #    "image"
        ]

class DeckForm(ModelForm):
    class Meta:
        model = Deck
        fields = (
            "folder",
            "name",
            "description",
        )
    def __init__(self, *args, **kwargs):
  #      self.user=kwargs.pop('user')
        super(DeckForm, self).__init__(*args, **kwargs)
#        self.fields['folder'].queryset=Folder.objects.none()
   #     def clean(self):
    #        cleaned_data=super().clean()
     #       folder_id=cleaned_data.get('folder')
      #      cleaned_data['folder']=Folder.objects.get(id=folder_id)

synctio/flashcards/views.py
from winreg import REG_OPTION_BACKUP_RESTORE
from xml.etree.ElementTree import TreeBuilder
from django.http import Http404, JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
# Create your views here.
from .models import Folder, Deck, Flashcard, FlashcardImpression
from .forms import DeckForm, FolderForm, FlashcardForm, findFlashcardForm, createDeckEmpty, createFolderEmpty
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import FlashcardSerializer, DeckSerializer, FolderSerializer, FlashcardImpressionSerializer
from django.views.generic import FormView
from rest_framework import generics
from rest_framework import status  # Import this for Status
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response  # Import this for Response
from rest_framework.viewsets import GenericViewSet
from rest_framework.views import APIView
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from synctio.settings import LOGIN_URL
from rest_framework import serializers
import random
from collections import OrderedDict

@login_required
def flashcardWordBlowing(request, pk):
    context={
        "deck":Deck.objects.get(id=pk).name
    }
    return render(request, "flashcards/windblowing.html", context)

@login_required
def flashcardCreateView(request):
    form=FlashcardForm(request.POST or None)
    if form.is_valid()==True:
        flashcard=Flashcard.objects.create(deck=form.cleaned_data.get("deck"), key=form.cleaned_data.get("key"), answer=form.cleaned_data.get("answer"))
        flashcard.save()
        return JsonResponse(FlashcardSerializer(flashcard).data, status=201)
    return JsonResponse({}, status=404)

@login_required
def folderCreateEmpty(request):
    form=createFolderEmpty(request.POST or None)
    if form.is_valid()==True:
        if form.cleaned_data.get("previous_folder")=="-1":
            folder=Folder.objects.create(previous_folder=None, user=request.user, name=form.cleaned_data.get("name"), description=form.cleaned_data.get("description"))
        else:
            folder=Folder.objects.create(previous_folder=Folder.objects.get(id=int(form.cleaned_data.get("previous_folder"))), user=request.user, name=form.cleaned_data.get("name"), description=form.cleaned_data.get("description"))
        folder.save()
 #       if folder.previous_folder==None:
 #           return JsonResponse({"previousfolderid":"-1", "foldername":folder.name, "folderid":str(folder.id)}, status=201)
 #       return JsonResponse({"previousfolderid":str(folder.previous_folder.id), "foldername":folder.name, "folderid":str(folder.id)}, status=201)
        return JsonResponse({}, status=201)
    return JsonResponse({}, status=404)

@login_required
def deckCreateEmpty(request):
    form=createDeckEmpty(request.POST or None)
    print(form.is_valid())
    print(form.errors)
    print(form.data)
    if form.is_valid()==True:
        print("form is valid")
        deck=Deck.objects.create(folder=Folder.objects.get(id=int(form.cleaned_data.get("folder"))), user=request.user, name=form.cleaned_data.get("name"), description=form.cleaned_data.get("description"))
        deck.save()
        for x in range(0, 3):
            Flashcard.objects.create(deck=deck, key="untitled", answer="untitled")
        return JsonResponse({"deckid":str(deck.id)}, status=201)
    return JsonResponse({}, status=404)

@login_required
def flashcardwriteview(request, pk):
    randomFlashcard=random.choice(Flashcard.objects.filter(deck=Deck.objects.get(id=pk)))
 #   print(FlashcardSerializer(randomFlashcard).data)
    context={
        "deck":Deck.objects.get(id=pk),
        "flashcard":FlashcardSerializer(randomFlashcard).data,
    }

    return render(request, "flashcards/flashcardwrite.html", context)

@login_required
def flashcardplayview(request, pk):
    randomFlashcard=random.choice(Flashcard.objects.filter(deck=Deck.objects.get(id=pk)))
 #   print(FlashcardSerializer(randomFlashcard).data)
    context={
        "deck":Deck.objects.get(id=pk),
        "flashcard":FlashcardSerializer(randomFlashcard).data,
    }

    return render(request, "flashcards/flashcardplay.html", context)


# class DeckApi(generics.ListAPIView):
#     queryset=Deck.objects.all()
#     serializer_class=DeckSerializer
#  #   def get_queryset(self):
#  #       return Deck.objects.filter(user=self.request.user)
# folders=Folder.objects.all()

# @api_view(['POST'])
# def FlashcardCreateView(request, pk):
#     serializer=FlashcardSerializer(data=request.POST or None)
#     if serializer.is_valid(raise_exception=True):
#         obj=serializer.save(deck=pk)
#         return Response(serializer.data)
#     return Response({}, status=400)

@login_required
def home(request):
    q=request.GET.get('q') if request.GET.get('q') != None else ""
    if q!="":
        decks=Deck.objects.filter(user=request.user)
        decks = decks.filter(
            Q(folder__name=q) |
            Q(description__icontains=q)|
            Q(name__icontains=q)
            )
    else:
        decks=Deck.objects.filter(user=request.user)
    global foldersHTML
    foldersHTML=""
    folders=Folder.objects.filter(user=request.user)
    def recurseDict(parent_folder, counter):
        global foldersHTML
        if parent_folder==None:
           for f in folders.filter(previous_folder__isnull=True):
                foldersHTML+="<details id='folder-"+str(f.id)+"'><summary><a href='?q="+f.name+"'>"+f.name+"</a><a class='deleteBtn' href='/delete-folder/"+str(f.id)+"/'><i class='fa-solid fa-trash'></i></a></summary>"
                recurseDict(f, counter+1)
                foldersHTML+="</details>" 
        else:
            for f in folders.filter(previous_folder__name=parent_folder):
                foldersHTML+="<details id='folder-"+str(f.id)+"'><summary><a href='?q="+f.name+"'>"+"&nbsp &nbsp"*counter+f.name+"</a><a class='deleteBtn' href='/delete-folder/"+str(f.id)+"/'><i class='fa-solid fa-trash'></i></a></summary>"
                recurseDict(f, counter+1)
                foldersHTML+="</details>"
    if len(folders)>0:
        recurseDict(None, 0)
    decks_count = decks.count()
    context={'decks': decks, "folders":folders, "decks_count":decks_count, "foldersHTML":foldersHTML, "form":createDeckEmpty()}
    return render(request, "flashcards/home.html", context)

#@login_required
#def createFolder(request):
#    form = FolderForm(request.POST or None)
#    if form.is_valid():
#        formcreate=form.save(commit=False)
#        formcreate.user=request.user
#        formcreate.save()
#        return redirect('home')
#    form=FolderForm()
#    context={'form': form}
#    return render(request, 'flashcards/deck_form.html', context)

@login_required
def deckView(request, pk):
    print(request.user.id)
    print(Deck.objects.get(id=pk).folder)
    print(Deck.objects.get(id=pk).folder.id)
    context={
        "pk":pk,
        "user":request.user.id,
        "folder":Deck.objects.get(id=pk).folder.id,
        "folderList":Folder.objects.filter(user=request.user)
    }
    return render(request, "flashcards/deck.html", context)

# class FolderList(generics.ListCreateAPIView):
#     queryset = Folder.objects.all()
#     serializer_class = FolderSerializer


# class FolderDetail(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Folder.objects.all()
#     serializer_class = FolderSerializer


# class DeckList(generics.ListCreateAPIView):
#     queryset=Deck.objects.all()
#     serializer_class = DeckSerializer

# class DeckDetail(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Deck.objects.all()
#     serializer_class = DeckSerializer

@login_required
def DeckDetail(request, pk):
    deck=Deck.objects.get(id=pk)
    if deck.user==request.user:
        return JsonResponse(DeckSerializer(deck).data, status=200)
    return JsonResponse({}, status=404)

@login_required
def FlashcardList(request, pk):
    deck=Deck.objects.get(id=pk)
    flashcards=Flashcard.objects.filter(deck=deck)
    if deck.user==request.user:
        flashcardList=[]
        for x in flashcards:
            flashcardList.append(FlashcardSerializer(x).data)
        return JsonResponse({"flashcards":flashcardList}, status=200)
    return JsonResponse({}, status=404)


# class FlashcardList(generics.ListCreateAPIView):
#     def get_queryset(self):
#         deck=self.kwargs["deck"]
#   #      longitude = self.request.query_params.get('longitude')
#         queryset = Flashcard.objects.filter(deck=deck)
#         print(queryset)
#         return queryset
#     serializer_class = FlashcardSerializer


# class FlashcardDetail(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Flashcard.objects.all()
#     def PUT(self, request, *args, **kwargs):
#         global queryset
#         flashcard = queryset
#         serializer = FlashcardSerializer(flashcard, data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return JsonResponse(serializer.data)
#         return JsonResponse(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
#     serializer_class = FlashcardSerializer

@login_required
def updateJsonFlashcard(request, pk):
    form=FlashcardSerializer(data=request.POST or None)
    print(form)
    print(form.is_valid())
    print(form.data)
    print(form.errors)
    print("id is", form.validated_data.get("deck"))

    if form.is_valid():
        print("id is", form.validated_data.get("deck"))
        if form.validated_data.get("deck").user.id==request.user.id:
            flashcard=Flashcard.objects.get(id=pk)

synctio/flashcards/templates/flashcards/deck.html
{% extends "main.html" %}
{% block headercontent %}
<script
  src="https://code.jquery.com/jquery-3.6.1.slim.min.js"
  integrity="sha256-w8CvhFs7iHNVUtnSP0YKEg00p9Ih13rlL9zGqvLdePA="
  crossorigin="anonymous"></script>



{% endblock headercontent %}
{% block stylecontent %}
    .flashcard{
        padding:10px;
        margin:10px;
    }
    #navbuttons{
      display: table;
      margin:auto;
      padding:10%;
    }
    #deckform{
      padding-top:5%;
    }
    .hoverinput{
      display:block;
      box-sizing:border-box;
      padding:5px;
      width:100%;
      border:none;
      margin:10px;
      border-radius:5px;
    }
    .hoverinput:hover{
      outline:3px solid lightgrey;

    }
    .hoverinput:focus{
      outline:3px solid grey;
    }
    #deckname{
      font-size: 1.5rem;
    }
    #deckdescription{
      color:grey;
    }
    .container{
      background-color:var(--violet);
      margin-top:10%;
      border-radius:30px;
      margin:auto;
      margin-top:5%;
      padding:5%;
      width:90%;
      box-sizing:border-box;
  }
{% endblock stylecontent %}
{% block content %}
<div class="container">
<div id="deck_wrapper">
  <form id="deckform" class="col-md-9 mx-auto col-10" method="POST" action="/deck-json-update/{{pk}}/">
    {%csrf_token%}
    <input id="deckname" class="hoverinput" type="text" value="deck name" name="name">
    <input id="deckdescription" class="hoverinput" type="text" value="deck description" name="description">
    <select id="deckfolder" class="hoverinput" type="text" name="folder">
      {% for f in folderList%}
        <option value="{{f.id}}">{{f.name}}</option>
      {% endfor %}
    </select>
    <input id="deckuser" type="text" value="{{user}}" name="user" hidden>
    <button id="deckSubmit" type="submit" hidden>Submit</button>
  </form>
</div>
<hr>
<div id="navbuttons" class="my-auto btn-group btn-group-lg" role="group" aria-label="NavButtons">
  <a href="{% url 'flashcardplay' pk %}" type="button" class="btn btn-primary">Cards</a>
  <a href="{% url 'flashcardwriteapi' pk %}" type="button" class="btn btn-primary">Text</a>
</div>

<hr>

<form id="flashcard_form" class="form col-md-9 mx-auto col-10" method="POST" action="{% url 'flashcardCreateView' %}">
</form>
<div id="flashcards_wrapper" class="grid gap-3">
</div>
<input type="hidden" value="/" name="next"/>
</div>
<script type="text/javascript">
const flashcards_wrapper=document.getElementById("flashcards_wrapper")
const deck_wrapper=document.getElementById("deck_wrapper")
const flashcard_form=document.getElementById("flashcard_form")
function format(obj){
  if (obj.answer==null){
    obj.answer=""
  }
  return `<div id="flashcardobj-`+obj.id+`" class="card flashcard col-md-6 mx-auto col-10"><div class="card-body"><input id="inputkey-`+obj.id+`" onchange='handleFlashcardEdit(`+JSON.stringify(obj).replace('"',"&quot;")+`)' type="text" class="flashcard_key hoverinput" value="`+obj.key.replace('"',"&quot;")+`"><input id="inputanswer-`+obj.id+`"type="text" onchange='handleFlashcardEdit(`+JSON.stringify(obj).replace('"',"&quot;")+`)' class="flashcard_description hoverinput" value="`+obj.answer.replace('"',"&quot;")+`"><br><button type="button" class="btn btn-warning" onclick="handleDelete(`+obj.id+`)">Delete</button></div></div>`
}
var stringToHTML = function (str) {
	var parser = new DOMParser();
    var doc = parser.parseFromString(str, 'text/html');
    return doc.body.getElementsByTagName("form")[0];
};
function handleFlashcardEdit(obj){
//  obj=JSON.parse(obj)
  let objkey=document.getElementById("inputkey-"+obj.id)
  let objanswer=document.getElementById("inputanswer-"+obj.id)
  const form=stringToHTML(`<form>{%csrf_token%}<input name="deck" value={{pk}}></input><input name="key" value="`+objkey.value+`"><input name="answer" value="`+objanswer.value+`"></form>`)
  console.log(form)
  const formData=new FormData(form)
  const url="/update-json-flashcard/"+obj.id+"/"
  const xhr= new XMLHttpRequest()
  const responseType="json"
  xhr.responseType=responseType
  xhr.open("POST", url)
  xhr.onload=function(){

  }
  xhr.send(formData)

}

function handleFlashcardFormDidSubmit(event){
    event.preventDefault()
    const form=event.target
    const formData=new FormData(form)
    const url = form.getAttribute("action")
    const method= form.getAttribute("method")
    const xhr = new XMLHttpRequest()
    const responseType="json"
    xhr.responseType=responseType
    xhr.open(method, url)
    xhr.setRequestHeader("x-Requested-With", "XMLHttpRequest")
    xhr.onload=function(){
        if (xhr.status===201){
        const newFlashcard = xhr.response
        flashcards_wrapper.innerHTML=format(newFlashcard)+flashcards_wrapper.innerHTML;
      }else if(xhr.status===400){
            flashcard_form.outerHTML="";
            flashcards_wrapper.outerHTML="";
            deck_wrapper.innerHTML="ERROR";
        }else if(xhr.status===500){
            flashcard_form.outerHTML="";
            flashcards_wrapper.outerHTML="";
            deck_wrapper.innerHTML="ERROR";
            alert("There was a server error, please try again.")
        }
    }
    xhr.onerror=function(){
        alert("An error occured. Please try again later.")
    }
    xhr.send(formData)
}
flashcard_form.addEventListener("submit", handleFlashcardFormDidSubmit)
function handleDelete(id){
  console.log(id)
  xhr=new XMLHttpRequest();
  const url="/delete-json-flashcard/"+id+'/'
  xhr.open("GET", url)
  xhr.onload=function(){
    if (xhr.status===201){
      document.getElementById("flashcardobj-"+id).outerHTML=""
    }else if(xhr.status===400){
      alert("error")
    }
    else if(xhr.status===500){
      alert("ERROR")
    }
  }
  xhr.send()
}




function loadDeck(deckform){
 // flashcards_wrapper.innerHTML="Loading..."
  const xhr=new XMLHttpRequest()
  const method="GET"
  const url="/deck-detail/{{pk}}/"
  const responseType="json"
  xhr.responseType=responseType
  xhr.open(method, url)
  xhr.onload=function(){
    var deck=xhr.response
    console.log(deck)
    document.getElementById("deckname").value=deck.name.replace('"', "&quot;")
    document.getElementById("deckdescription").value=deck.description.replace('"', "&quot;")
    document.getElementById("deckfolder").value=deck.folder
    console.log(deck.folder);
//    document.getElementById("deckform").addEventListener("submit", handleDeckFormDidSubmit)
document.getElementById("deckdescription").addEventListener("change", function(event){
  let deckform=document.getElementById("deckform")
  event.preventDefault();
  console.log(deckform)
  handleDeckFormDidSubmit(deckform)
})
document.getElementById("deckname").addEventListener("change", function(event){
      let deckform=document.getElementById("deckform")
      event.preventDefault();
      console.log(deckform)
      handleDeckFormDidSubmit(deckform)
    })
    document.getElementById("deckfolder").addEventListener("change", function(event){
      let deckform=document.getElementById("deckform")
      event.preventDefault();
      console.log(deckform)
      handleDeckFormDidSubmit(deckform)
    })
  }
  xhr.send()
}
//let deckform=document.getElementById("deckform")
loadDeck(deckform)
function handleDeckFormDidSubmit(deckform){
 // event.preventDefault()
  const form=deckform
  console.log(form)
  const formData=new FormData(form)
  const url = form.getAttribute("action")
  const method= form.getAttribute("method")
  const xhr = new XMLHttpRequest()
  const responseType="json"
  xhr.responseType=responseType
  xhr.open(method, url)
  xhr.setRequestHeader("x-Requested-With", "XMLHttpRequest")
  xhr.onload=function(){
    console.log("deckload")
      if (xhr.status===201){
        console.log(xhr.response)
    }else if(xhr.status===400){
//          flashcard_form.outerHTML="";
//          flashcards_wrapper.outerHTML="";
//          deck_wrapper.innerHTML="ERROR";
      }else if(xhr.status===500){
//          flashcard_form.outerHTML="";
//          flashcards_wrapper.outerHTML="";
//          deck_wrapper.innerHTML="ERROR";
//          alert("There was a server error, please try again.")
      }
  }
  xhr.onerror=function(){
      alert("An error occured. Please try again later.")
  }
  xhr.send(formData)
}


function loadFlashcards(flashcards_wrapper, deck_wrapper, flashcard_form){
  //  deck_wrapper.innerHTML='Loading...'
  //  flashcards_wrapper.innerHTML="Loading..."
    const xhr=new XMLHttpRequest()
    const method="GET"
    const url="/flashcard-list/{{pk}}/"
    const responseType="json"
    xhr.responseType=responseType
    xhr.open(method, url)
    xhr.onload=function(){
      var listedItems=xhr.response["flashcards"]
      console.log(xhr.response)
      flashcard_form.innerHTML=`
      {% csrf_token%}
    <input required="required" class="hoverinput" name="key" placeholder="prompt">
    <input class="hoverinput" name="answer" placeholder="answer">
    <input name="deck" type="hidden" value="{{pk}}">
    <button type="submit" class="btn btn-primary">Add</button><hr>`
      for(var i=0; i<listedItems.length; i++){
        let flashcardObj=listedItems[i]
        flashcards_wrapper.innerHTML+=format(flashcardObj)
      }
    }
    xhr.send()
}
loadFlashcards(flashcards_wrapper, deck_wrapper, flashcard_form)

</script>
{% endblock content %}

synctio/flashcards/templates/flashcards/deck_form.html
{% extends 'main.html' %}

{% block content %}
<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Make new Deck">
    </form>
</div>
<script>
    const foldersobj=document.querySelector('[name="folder"]')
    foldersobj.outerHTML=`
    <select id="id_folder" name='folder'>
    {% for folder in folders %}
        <option value='{{folder.id}}'>{{folder.name}}</option>
    {% endfor %}
    </select>
    `
</script>

{% endblock content %}

synctio/flashcards/templates/flashcards/delete.html
{% extends 'main.html'%}

{% block content %}

<form method="POST" action="">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{obj.name}}"?</p>
    <p>This action will delete everything inside of it as well.</p>
    <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

synctio/flashcards/templates/flashcards/form.html
{% extends 'main.html'%}

{% block content %}

<form method="POST" action="">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>
{% endblock content %}